name: deploy-toy-website-end-to-end
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  # Build the application and database.
  build:
    uses: cshaigh/toy-website-end-to-end/.github/workflows/build.yml@main

  # Lint the Bicep file.
  lint:
    uses: cshaigh/toy-website-end-to-end/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: cshaigh/toy-website-end-to-end/.github/workflows/deploy.yml@main
    needs:
    - lint    
    - build

    with:
      environmentType: Test
      resourceGroupName: ChrisToyWebsiteTest
      reviewApiUrl: https://sandbox.contoso.com/reviews

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: cshaigh/toy-website-end-to-end/.github/workflows/deploy.yml@main
    needs:
    - lint
    - build
    - deploy-test

    with:
      environmentType: Production
      resourceGroupName: ChrisToyWebsiteProduction
      reviewApiUrl: https://api.contoso.com/reviews

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
